server:
  port: 8081
  contextPath: /App

spring.jpa.hibernate.ddl-auto: update
spring:
  #DB connection properties
  datasource:
    url: jdbc:mysql://localhost:3306/billing
    username: root
    password: nts@digital
    driver-class-name: com.mysql.jdbc.Driver

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect